# Generated by Django 4.2.1 on 2023-06-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
                ('telefone', models.IntegerField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
