# Generated by Django 4.2.1 on 2023-06-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalhe_turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAluno', models.IntegerField()),
                ('codigoProfessor', models.IntegerField()),
                ('codigoTurma', models.IntegerField()),
            ],
        ),
    ]
